GET http://localhost:3000/v1/tasks?page=1&status=Todo
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAdGVzdC5jb20iLCJleHAiOjE3NDkxMTg0NzV9.svx_Enb9MjJjNI92lmTzt5TlgQD-RCj2vAaZxDab9Dg